spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  rabbitmq:
    ssl:
      enabled: true

server:
  error:
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: WARN
    com.ziboto: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false